image: golang:latest

pages:
  artifacts:
    paths:
      - public
  only:
    - master

  before_script:
    - git clone https://git.sr.ht/~sircmpwn/openring
    - cd openring
    - go build -o openring
    - cp openring /usr/local/bin/
    - cd ..
    - git clone https://git.sr.ht/~sircmpwn/hugo
    - cd hugo
    - go build -o hugo
    - cp hugo /usr/local/bin/
    - cd ..

  script: 
    - |
      /usr/local/bin/openring \
        -s https://emersion.fr/blog/rss.xml \
        -s https://ssene.ca/atom.xml \
        -s https://drewdevault.com/blog/index.xml \
        < webring-in.template \
        > layouts/partials/webring-out.html 
    - /usr/local/bin/hugo


