baseURL = "https://jonathanbartlett.co.uk"
title = "Jonathan Bartlett's Musings"
pygmentsUseClasses = true
uglyurls = true
disablePathToLower = true

[taxonomies]
tag = "tags"

[permalinks]
blog = "/:year/:month/:day/:filename"

[markup.goldmark.renderer]
unsafe = true

[markup.tableOfContents]
ordered = true
endLevel = 3
startLevel = 2

[outputs]
section = ["HTML", "RSS"]
