baseURL = "https://jonathanbartlett.co.uk"
title = "Jonathan Bartlett's Musings"
pygmentsUseClasses = true
uglyurls = true
disablePathToLower = true

[permalinks]
blog = "/:year/:month/:day/:filename"

[markup.goldmark.renderer]
unsafe = true

[markup.tableOfContents]
ordered = true

[outputs]
section = ["HTML", "RSS"]
